<script setup>
import { ref } from 'vue'
const copied = ref(false)
const paper = { title:'H3-World:', subtitle:'Turning Language Understanding into World Control', summary:'H3-World enables character and camera control across diverse visual environments.', venue:'Interactive World Models' }
const authors = [{name:'Danze Chen',mark:'1,2,♣'},{name:'Zeqing Wang',mark:'1,2,♣'},{name:'Ziyue Lin',mark:'3'},{name:'Xingyi Yang',mark:'3,*'},{name:'Yeying Jin',mark:'1,2,*,♦'}]
const links = [{label:'Project',icon:'↗',href:'https://github.com/Danzer1xxxxChan/H3-World'},{label:'GitHub',icon:'⌘',href:'https://github.com/Danzer1xxxxChan/H3-World'},{label:'Hugging Face',icon:'☺',href:'https://huggingface.co/DANNY621/H3-World'}]
const demos = [{label:'Scene understanding',note:'Replace with your first qualitative result',tone:'sage'},{label:'Controllable generation',note:'Replace with an interactive demo or video',tone:'blue'},{label:'Long-horizon consistency',note:'Replace with a long-form comparison',tone:'amber'},{label:'Open-world generalization',note:'Replace with an unseen-domain result',tone:'rose'}]
const gallery = [['Input → Output','Main qualitative comparison','g1'],['Ablation study','Contribution of each component','g2'],['Generalization','Results on unseen data','g3'],['Comparison','Against the strongest baseline','g4'],['Efficiency','Runtime and memory profile','g5'],['Failure cases','Limitations and future work','g6']]
const bibtex = `@misc{chen2026h3world,
  title     = {H3-World: Turning Language Understanding into World Control},
  author    = {Danze Chen and Zeqing Wang and Ziyue Lin and Xingyi Yang and Yeying Jin},
  year      = {2026}
}`
async function copyBibtex(){await navigator.clipboard.writeText(bibtex);copied.value=true;window.setTimeout(()=>copied.value=false,1600)}
</script>
<template><main>
  <header class="hero page-width"><div class="venue-pill">{{paper.venue}} · PROJECT PAGE</div><h1><span>{{paper.title}}</span>{{paper.subtitle}}</h1><p class="summary">{{paper.summary}}</p><div class="authors"><a v-for="author in authors" :key="author.name" href="#">{{author.name}}<sup>{{author.mark}}</sup></a></div><div class="affiliations"><span><sup>1</sup> Tencent</span><span><sup>2</sup> National University of Singapore</span><span><sup>3</sup> The Hong Kong Polytechnic University</span></div><div class="author-notes"><span>♣ Research internship at Tencent</span><span>* Corresponding authors</span><span>♦ Project leader</span></div><nav class="link-row" aria-label="Publication links"><a v-for="link in links" :key="link.label" :href="link.href" target="_blank" rel="noopener noreferrer"><span>{{link.icon}}</span>{{link.label}}</a></nav></header>
  <section class="page-width hero-media" aria-label="Paper teaser"><figure class="teaser-figure"><img src="/h3-world-teaser.jpg" alt="H3-World teaser showing a snowy mountain world, a neon city, a desert oasis, and a greenhouse environment"><figcaption><strong>H3-World</strong> enables character and camera control across diverse visual environments.</figcaption></figure></section>
  <section class="page-width section" id="demo"><div class="section-heading"><span>01</span><div><h2>Our method turns ideas<br>into consistent results</h2><p>Use this area to state the paper's most memorable capability in one sentence.</p></div></div><div class="demo-grid"><article v-for="(demo,index) in demos" :key="demo.label" class="demo-card"><div class="demo-visual" :class="demo.tone"><span class="demo-index">0{{index+1}}</span><div class="demo-shape"></div><span class="play">▶</span></div><h3>{{demo.label}}</h3><p>{{demo.note}}</p></article></div></section>
  <section class="paper-section" id="abstract"><div class="page-width text-layout"><div class="side-label"><span>02</span> ABSTRACT</div><div><h2>Abstract</h2><p class="abstract-lead">We introduce <strong>Your Method</strong>, a unified framework for an important research problem.</p><p>Replace this paragraph with your paper abstract. Establish the problem, identify the limitation of existing approaches, explain the central technical idea, and end with the most important experimental result.</p><p>建议直接粘贴英文摘要，并将最关键的方法名称、数据规模或性能提升用粗体强调。这里的内容仅用于展示版式，不代表真实研究结论。</p><div class="highlight"><span>KEY TAKEAWAY</span><strong>Summarize the single result you want every visitor to remember.</strong></div></div></div></section>
  <section class="page-width section" id="method"><div class="section-heading"><span>03</span><div><h2>Method overview</h2><p>A clear three-stage pipeline helps readers understand the contribution before reading the paper.</p></div></div><div class="pipeline-card"><div class="pipeline-stage"><span>01</span><div class="pipeline-icon">IN</div><h3>Observe</h3><p>Encode the input and preserve the information needed downstream.</p></div><div class="connector">→</div><div class="pipeline-stage featured"><span>02</span><div class="pipeline-icon">YM</div><h3>Your Method</h3><p>Apply the key technical contribution and structured reasoning process.</p></div><div class="connector">→</div><div class="pipeline-stage"><span>03</span><div class="pipeline-icon">OUT</div><h3>Predict</h3><p>Produce coherent, accurate, and controllable outputs.</p></div></div><p class="caption">Figure 1. Replace this diagram with the method overview from your paper.</p></section>
  <section class="results-band" id="results"><div class="page-width section"><div class="section-heading light-heading"><span>04</span><div><h2>Results gallery</h2><p>Present qualitative comparisons, ablations, generalization, and limitations in a scan-friendly grid.</p></div></div><div class="gallery-grid"><figure v-for="item in gallery" :key="item[0]"><div class="gallery-visual" :class="item[2]"><span>{{item[0]}}</span><b>RESULT<br>MEDIA</b></div><figcaption><strong>{{item[0]}}</strong><span>{{item[1]}}</span></figcaption></figure></div></div></section>
  <section class="page-width section citation" id="citation"><div class="section-heading"><span>05</span><div><h2>BibTeX</h2><p>If you find this work useful, please consider citing it.</p></div></div><div class="bibtex-card"><button @click="copyBibtex">{{copied?'Copied ✓':'Copy BibTeX'}}</button><pre>{{bibtex}}</pre></div></section>
  <footer><div class="page-width"><span>H3-WORLD · 2026</span><p>Turning Language Understanding into World Control.</p><a href="#">Back to top ↑</a></div></footer>
</main></template>
