<script setup>
import { ref } from 'vue'
const copied = ref(false)
const baseUrl = import.meta.env.BASE_URL
const paper = { title: 'H3-World', subtitle: 'Turning Language Understanding into World Control', statement: 'Turn keyboard input into temporally grounded, controllable video.' }
const authors = [{ name: 'Danze Chen', mark: '1,2,♣' }, { name: 'Zeqing Wang', mark: '1,2,♣' }, { name: 'Ziyue Lin', mark: '3' }, { name: 'Xingyi Yang', mark: '3,*' }, { name: 'Yeying Jin', mark: '1,2,*,♦' }]
const links = [{ label: 'Project', href: 'https://github.com/Danzer1xxxxChan/H3-World' }, { label: 'Code', href: 'https://github.com/Danzer1xxxxChan/H3-World' }, { label: 'Hugging Face', href: 'https://huggingface.co/DANNY621/H3-World' }]
const demos = [{ label: 'Fast pan right', scene: 'Neon alley', note: 'First-person camera control.', video: 'demos/katana-neon-alley-forward.mp4' }, { label: 'Strafe left', scene: 'Lantern cave', note: 'First-person lateral movement.', video: 'demos/lantern-cave-forward.mp4' }, { label: 'Strafe right', scene: 'Dune oasis', note: 'Third-person lateral navigation.', video: 'demos/dune-oasis-forward.mp4' }, { label: 'Tilt up', scene: 'Cathedral paladin', note: 'Third-person upward camera motion.', video: 'demos/cathedral-paladin-forward.mp4' }]
const bibtex = `@misc{chen2026h3world,
  title     = {H3-World: Turning Language Understanding into World Control},
  author    = {Danze Chen and Zeqing Wang and Ziyue Lin and Xingyi Yang and Yeying Jin},
  year      = {2026}
}`
async function copyBibtex() { await navigator.clipboard.writeText(bibtex); copied.value = true; window.setTimeout(() => copied.value = false, 1600) }
</script>

<template>
  <main id="top">
    <header class="site-nav"><a class="brand" href="#top"><span>✦</span> H3-World</a><nav aria-label="Primary navigation"><a href="#abstract">Abstract</a><a href="#insight">Control</a><a href="#method">Architecture</a><a href="#demos">Demos</a><a href="#temporal">Temporal</a></nav><span class="nav-year">PROJECT · 2026</span></header>
    <section class="hero" aria-label="H3-World project introduction"><img class="hero-backdrop" :src="baseUrl + 'h3-world-teaser.jpg'" alt=""><div class="hero-shade"></div><div class="hero-content page-width"><p class="eyebrow">INTERACTIVE WORLD MODELS · PROJECT PAGE</p><h1>{{ paper.title }}<span>{{ paper.subtitle }}</span></h1><p class="hero-statement">{{ paper.statement }}</p><p class="authors"><a v-for="author in authors" :key="author.name" href="#top">{{ author.name }}<sup>{{ author.mark }}</sup></a></p><p class="affiliations"><sup>1</sup> Tencent <span>·</span> <sup>2</sup> National University of Singapore <span>·</span> <sup>3</sup> The Hong Kong Polytechnic University</p><p class="author-notes">♣ Research internship at Tencent &nbsp; · &nbsp; * Corresponding authors &nbsp; · &nbsp; ♦ Project leader</p><div class="link-row"><a v-for="link in links" :key="link.label" :href="link.href" target="_blank" rel="noopener noreferrer">{{ link.label }} <span>↗</span></a></div></div></section>
    <section id="abstract" class="paper-section"><div class="page-width split-section"><p class="section-index">01 / PAPER SUMMARY</p><div><h2>Abstract</h2><p class="lead">H3-World is an action-controllable world model that turns keyboard input into temporally grounded video control.</p><p>Built by fine-tuning MiniMax-H3 on gameplay footage, H3-World converts character and camera actions into a short English instruction for every video latent frame. A directed attention mask binds each instruction to its corresponding frame, enabling precise action-to-motion control without adding action-specific modules.</p><p>Only a rank-32 LoRA is trained on self-attention projections. This lightweight adaptation lets the same first frame produce different, coherent trajectories under different keyboard schedules.</p></div></div></section>
    <section id="insight" class="dark-section"><div class="page-width section-block"><p class="section-index">02 / THE CONTROL GAP</p><h2>Plausible motion is not enough.</h2><p class="section-intro">A world model must understand not only <em>what</em> action is requested, but also <em>when</em> it should happen.</p><div class="insight-grid"><article><span>01</span><h3>Global prompt</h3><p>One sentence can suggest motion, but it cannot reliably assign different actions to different moments.</p></article><article><span>02</span><h3>Per-latent text</h3><p>A temporal interface alone is insufficient: a frozen model does not yet act on this new input format.</p></article><article class="accent-card"><span>03</span><h3>H3-World</h3><p>LoRA adaptation and directed attention turn language instructions into frame-aligned world control.</p></article></div></div></section>
    <section id="method" class="page-width section-block"><p class="section-index">03 / ARCHITECTURE</p><h2>Language becomes a control sequence.</h2><p class="section-intro">Visual tokens and action descriptions share one packed H3 sequence; each language instruction is directed to its matching video latent.</p><figure class="feature-figure"><img :src="baseUrl + 'h3-world-method.png'" alt="H3-World method diagram showing packed visual and action streams, H3 block adaptation, LoRA, and directed masked attention"><figcaption><strong>How it works.</strong> We encode actions as natural-language conditions, bind them to the right temporal positions with a directed mask, and adapt only the H3 self-attention projections with LoRA.</figcaption></figure></section>
    <section id="demos" class="demo-section"><div class="page-width section-block"><p class="section-index">04 / WORLD CONTROL IN ACTION</p><h2>One interface, diverse worlds.</h2><p class="section-intro">The same action language controls camera and character motion across scenes, viewpoints, and visual styles.</p><div class="demo-grid"><article v-for="(demo, index) in demos" :key="demo.scene"><div class="demo-visual"><span>0{{ index + 1 }}</span><video :src="baseUrl + demo.video" controls autoplay muted loop playsinline preload="metadata">Your browser does not support HTML video.</video></div><h3>{{ demo.label }}</h3><p><strong>{{ demo.scene }}</strong> · {{ demo.note }}</p></article></div></div></section>
    <section id="temporal" class="paper-section"><div class="page-width section-block"><p class="section-index">05 / TEMPORAL CONTROL</p><h2>Follow a schedule, not just a direction.</h2><p class="section-intro">The camera is instructed to pan sharply left first, then sharply right. Only H3-World follows both actions in their requested intervals.</p><figure class="feature-figure temporal-figure"><img :src="baseUrl + 'h3-world-temporal-control.png'" alt="Comparison of global prompting, per-latent prompting, and H3-World for a camera pan that switches from left to right"><figcaption><strong>Action response before and after adaptation.</strong> Global prompting provides a coarse response, while a frozen per-latent interface is nearly static. H3-World controls both action direction and timing.</figcaption></figure><div class="control-summary"><div><strong>Global prompt</strong><span>Motion response without temporal precision.</span></div><div><strong>Per-latent, no LoRA</strong><span>Temporal interface, but almost no motion.</span></div><div><strong>H3-World</strong><span>Action control and temporal control together.</span></div></div></div></section>
    <section id="citation" class="page-width section-block citation"><p class="section-index">06 / CITATION</p><h2>BibTeX</h2><div class="bibtex-card"><button @click="copyBibtex">{{ copied ? 'Copied ✓' : 'Copy BibTeX' }}</button><pre>{{ bibtex }}</pre></div></section>
    <footer><div class="page-width"><span>H3-WORLD · 2026</span><p>Turning language understanding into world control.</p><a href="#top">Back to top ↑</a></div></footer>
  </main>
</template>
