<script setup>
import { ref } from 'vue'
const copied = ref(false)
const baseUrl = import.meta.env.BASE_URL
const paper = { title:'H3-World:', subtitle:'Turning Language Understanding into World Control', summary:'H3-World enables character and camera control across diverse visual environments.', venue:'Interactive World Models' }
const authors = [{name:'Danze Chen',mark:'1,2,♣'},{name:'Zeqing Wang',mark:'1,2,♣'},{name:'Ziyue Lin',mark:'3'},{name:'Xingyi Yang',mark:'3,*'},{name:'Yeying Jin',mark:'1,2,*,♦'}]
const links = [{label:'Project',icon:'↗',href:'https://github.com/Danzer1xxxxChan/H3-World'},{label:'GitHub',icon:'⌘',href:'https://github.com/Danzer1xxxxChan/H3-World'},{label:'Hugging Face',icon:'☺',href:'https://huggingface.co/DANNY621/H3-World'}]
const demos = [{label:'Neon alley · fast pan right',note:'First-person camera control in a neon-lit city.',video:'demos/katana-neon-alley-forward.mp4'},{label:'Lantern cave · strafe left',note:'First-person lateral movement in a complex cave environment.',video:'demos/lantern-cave-forward.mp4'},{label:'Dune oasis · strafe right',note:'Third-person lateral navigation across an open desert scene.',video:'demos/dune-oasis-forward.mp4'},{label:'Cathedral paladin · tilt up',note:'Third-person upward camera motion in a detailed fantasy interior.',video:'demos/cathedral-paladin-forward.mp4'}]
const bibtex = `@misc{chen2026h3world,
  title     = {H3-World: Turning Language Understanding into World Control},
  author    = {Danze Chen and Zeqing Wang and Ziyue Lin and Xingyi Yang and Yeying Jin},
  year      = {2026}
}`
async function copyBibtex(){await navigator.clipboard.writeText(bibtex);copied.value=true;window.setTimeout(()=>copied.value=false,1600)}
</script>
<template><main>
  <header class="hero page-width"><div class="venue-pill">{{paper.venue}} · PROJECT PAGE</div><h1><span>{{paper.title}}</span>{{paper.subtitle}}</h1><p class="summary">{{paper.summary}}</p><div class="authors"><a v-for="author in authors" :key="author.name" href="#">{{author.name}}<sup>{{author.mark}}</sup></a></div><div class="affiliations"><span><sup>1</sup> Tencent</span><span><sup>2</sup> National University of Singapore</span><span><sup>3</sup> The Hong Kong Polytechnic University</span></div><div class="author-notes"><span>♣ Research internship at Tencent</span><span>* Corresponding authors</span><span>♦ Project leader</span></div><nav class="link-row" aria-label="Publication links"><a v-for="link in links" :key="link.label" :href="link.href" target="_blank" rel="noopener noreferrer"><span>{{link.icon}}</span>{{link.label}}</a></nav></header>
  <section class="page-width hero-media" aria-label="Paper teaser"><figure class="teaser-figure"><img :src="baseUrl + 'h3-world-teaser.jpg'" alt="H3-World teaser showing diverse visual environments"></figure></section>
  <section class="page-width section" id="demo"><div class="section-heading"><span>01</span><div><h2>Interactive world-control demos</h2><p>H3-World follows camera and character actions across diverse, open-ended visual environments.</p></div></div><div class="demo-grid"><article v-for="(demo,index) in demos" :key="demo.label" class="demo-card"><div class="demo-visual"><span class="demo-index">0{{index+1}}</span><video :src="baseUrl + demo.video" controls autoplay muted loop playsinline preload="metadata">Your browser does not support HTML video.</video></div><h3>{{demo.label}}</h3><p>{{demo.note}}</p></article></div></section>
  <section class="paper-section" id="abstract"><div class="page-width text-layout"><div class="side-label"><span>02</span> ABSTRACT</div><div><h2>Abstract</h2><p class="abstract-lead">We introduce <strong>H3-World</strong>, an action-controllable world model that turns keyboard input into temporally grounded video control.</p><p>Built by fine-tuning MiniMax-H3 on gameplay footage, H3-World converts character and camera actions into a short English instruction for every video latent frame. These instructions are injected through the pretrained text pathway and aligned to their corresponding frames with a directed attention mask, enabling precise action-to-motion binding without adding action-specific trainable modules.</p><p>Only a rank-32 LoRA is trained on the self-attention projections. This lightweight adaptation produces controllable motion from the same initial frame under different action sequences, while supporting longer-horizon generation and generalization across diverse visual environments.</p><div class="highlight"><span>KEY TAKEAWAY</span><strong>Language-aligned action control enables a single world model to translate keyboard inputs into coherent, controllable video dynamics.</strong></div></div></div></section>
  <section class="page-width section" id="method"><div class="section-heading"><span>03</span><div><h2>How H3-World works</h2><p>H3-World aligns language descriptions of keyboard actions with video latents, then adapts the pretrained H3 transformer with a lightweight LoRA.</p></div></div><figure class="method-figure"><img :src="baseUrl + 'h3-world-method-hires.png'" alt="H3-World method diagram"><figcaption><strong>Figure 1.</strong> H3-World packs visual tokens and latent-aligned action language into one sequence. A directed attention mask binds each action description to its corresponding visual latent, while LoRA adapts the H3 self-attention projections. <a :href="baseUrl + 'h3-world-method.pdf'" target="_blank">Open PDF ↗</a></figcaption></figure></section>
  <section class="paper-section" id="temporal-control"><div class="page-width section"><div class="section-heading"><span>04</span><div><h2>Temporally specified control</h2><p>H3-World follows different camera instructions at different moments within the same video.</p></div></div><figure class="method-figure"><img :src="baseUrl + 'h3-world-temporal-control.png'" alt="Temporal control comparison"><figcaption><strong>Figure 2.</strong> The instruction requests a sharp left pan in the first half and a sharp right pan in the second half. Global prompting provides coarse motion but misses the scheduled switch. The frozen per-latent interface remains nearly static. <strong>H3-World follows both actions in their requested time intervals.</strong></figcaption></figure><div class="control-summary"><div><strong>Global prompt</strong><span>Responds to motion, but not to the full schedule.</span></div><div><strong>Per-latent, no LoRA</strong><span>Has the interface, but produces almost no motion.</span></div><div><strong>H3-World</strong><span>Controls action direction and when each action happens.</span></div></div></div></section>
  <section class="page-width section" id="action-controllability"><div class="section-heading"><span>05</span><div><h2>Action controllability</h2><p>Grounding actions in the pretrained language pathway yields coordinated character motion and camera control.</p></div></div><figure class="method-figure"><img :src="baseUrl + 'h3-world-action-conditioning-hires.png'" alt="Comparison of direct action conditioning and H3-World"><figcaption><strong>Figure 3.</strong> Action-conditioning interfaces on a held-out gameplay clip. Direct additive-bias and FiLM conditioning lead to limited or inconsistent responses to the recorded keyboard controls. <strong>Text-based H3-World produces coordinated character and camera changes throughout the sequence.</strong> <a :href="baseUrl + 'h3-world-feature-injection.pdf'" target="_blank">Open PDF ↗</a></figcaption></figure><div class="control-summary"><div><strong>Additive bias</strong><span>Adding action vectors to video features yields weak and unreliable control.</span></div><div><strong>FiLM conditioning</strong><span>Feature-wise modulation can cause incorrect movement or camera responses.</span></div><div><strong>H3-World</strong><span>Language-grounded actions preserve the scene while following the recorded controls.</span></div></div></section>
  <section class="paper-section" id="generalization"><div class="page-width section"><div class="section-heading"><span>06</span><div><h2>Compositional generalization</h2><p>H3-World combines familiar character and camera primitives into action pairs never observed during training.</p></div></div><figure class="method-figure"><img :src="baseUrl + 'h3-world-compositional-generalization-hires.png'" alt="Seen and unseen compositional action generalization"><figcaption><strong>Figure 4.</strong> Compositional action generalization on held-out gameplay and out-of-distribution observations. H3-World follows an unseen combination of observed character and camera clauses while retaining the initial scene content. <a :href="baseUrl + 'h3-world-action-generalization.pdf'" target="_blank">Open PDF ↗</a></figcaption></figure><div class="generalization-note"><strong>Beyond seen combinations.</strong><span>Although the unseen action pair never appears in training, both of its components are familiar. H3-World composes them into coherent control in gameplay and new visual worlds.</span></div></div></section>
  <section class="page-width section citation" id="citation"><div class="section-heading"><span>07</span><div><h2>BibTeX</h2><p>If you find this work useful, please consider citing it.</p></div></div><div class="bibtex-card"><button @click="copyBibtex">{{copied?'Copied ✓':'Copy BibTeX'}}</button><pre>{{bibtex}}</pre></div></section>
  <footer><div class="page-width"><span>H3-WORLD · 2026</span><p>Turning Language Understanding into World Control.</p><a href="#">Back to top ↑</a></div></footer>
</main></template>
